package com.example.camera.engine.eisplus

import android.graphics.Rect

/**
 * Real-time 6-DoF fused stabilization transform generated by EisPlusStabilizationEngine.
 * Synchronized with camera exposure midpoint, OIS displacement, and rolling shutter skew.
 */
data class EisPlusTransform(
    val timestampNanos: Long = 0L,
    val ptsUs: Long = 0L,
    val dxNorm: Float = 0f,          // Normalized horizontal shift in [-1f, 1f]
    val dyNorm: Float = 0f,          // Normalized vertical shift in [-1f, 1f]
    val rotationDeg: Float = 0f,     // In-plane counter-rotation in degrees
    val scaleFactor: Float = 1.08f,  // Dynamic crop scale factor to prevent black borders
    val shearX: Float = 0f,          // Rolling shutter horizontal shear correction
    val shearY: Float = 0f,          // Rolling shutter vertical slant correction
    val isTripodMode: Boolean = false, // Aggressive low-motion tripod lock active
    val tripodConfidence: Float = 0f,  // 0f (handheld movement) to 1f (rock-steady tripod)
    val cropRect: Rect? = null,        // Stabilized crop on active sensor array
    val recentRmsSpeed: Float = 0f,    // Filtered angular velocity (rad/s)
    val oisFused: Boolean = false      // Hardware voice-coil OIS fused
)

/**
 * Frame-by-frame trajectory point recorded during video capture for exact GPU playback.
 */
data class EisPlusTrajectoryPoint(
    val ptsUs: Long,
    val timestampNanos: Long,
    val dxNorm: Float,
    val dyNorm: Float,
    val rotationDeg: Float,
    val scaleFactor: Float,
    val shearX: Float,
    val shearY: Float
)

/**
 * Live diagnostic telemetry exposed to UI for real-time stabilization HUD.
 */
data class EisPlusTelemetry(
    val isGyroActive: Boolean = false,
    val isOisFused: Boolean = false,
    val isTripodLocked: Boolean = false,
    val rmsMotionRadS: Float = 0f,
    val dynamicCropMarginPercent: Int = 8,
    val sampleRateHz: Int = 200,
    val rollingShutterCompensated: Boolean = true
)
